import Footer from "@/components/layout/footer";
import Header from "@/components/layout/header";
import ScrollProgressBar from "@/components/ui/scroll-progress-bar";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { ReactNode } from "react";
import { FONT_JP } from "@/styles/fonts";
import Providers from "../providers";
import ThemeSelector from "@/components/ui/theme-selector";
import PageChanger from "@/components/ui/page-changer";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <html
      lang="ja"
      className="w-full overflow-x-hidden scroll-smooth"
      suppressHydrationWarning={true}
    >
      <body className={FONT_JP}>
        <Providers>
          <ThemeSelector />

          <ScrollProgressBar />
          <Header />
          <PageChanger />

          <main className="container max-w-screen-xl overflow-x-hidden lg:overflow-x-visible">
            {children}
          </main>

          <Footer />
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
