import Footer from "@/components/layout/footer";
import Header from "@/components/layout/header";
import ScrollProgressBar from "@/components/ui/scroll-progress-bar";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { ReactNode } from "react";
import { FONT_JP } from "@/styles/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="ja" className="scroll-smooth w-full overflow-x-hidden">
      <body className={FONT_JP}>
        <ScrollProgressBar />
        <Header />
        <main className="container overflow-x-hidden lg:overflow-x-visible max-w-screen-xl">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
