import Footer from "@/components/layout/footer";
import Header from "@/components/layout/header";
import ScrollProgressBar from "@/components/ui/scroll-progress-bar";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="ja">
      <body>
        <ScrollProgressBar />
        <Header />
        <main className="container max-w-screen-xl h-[9999px]">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
